wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1641153828
    t:
      1:
      - 1
      - 4
      - 5
      3:
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 3
      - 5
bs:
  desc: null
  value: 1
dataset:
  desc: null
  value: dataset-sample
epochs:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0001
name:
  desc: null
  value: baseline-fastai
pretrained:
  desc: null
  value: true
size:
  desc: null
  value: 300
wd:
  desc: null
  value: 0.01
